var kStrings =
{
    flowersteleporter: "[STATE:garden=teleport][COLLECT:teleporter][SET:flowers.desc=flowersempty]Recalling where you saw the blinking light you rummage among the {flowers} and pull out an entry-level {teleporter} which you misplaced somewhere in your drop-pod years ago. It must have fallen out during the impact. It's one of those ones which doesn't even need a quantum link to an activated receiving station; just remembers all the places it's been and then lets you jump back to 'em.",
    flowersempty: "You search around the area where you picked up the {teleporter} hoping to find some more missing pieces. There are none.",
	landinghandle: "On the floor sits the detached {bedroomdoorhandle}.",
	landingloftopen: "The landing is now flooded with daylight thanks to the {openhatch} which hangs open above you.",
	handlecollect: "You pick up the detached {bedroomdoorhandle}. It's not as spherical as it once was - not after that wallop you gave it.",
	handledented: "The metal door handle is still cold to the touch but is no longer perfectly round. Looks like someone smacked it with a banister or something.",
	intobedroom: "Heavy {landingrubble} blocks everything apart from the open {bedroomjustdoor} leading into the {bedroom}.",
	pmm: "perpetual motion device",
	pmmdesc: "[SET:pmm.nothing=pmmnothing]The machine is still and silent.",
	pmmfixed: "The machine is humming quietly to itself, its wheels and cogs spinning endlessly thanks to the newly-repaired {flywheelbox} which sits at its core.",
	pmmnothing: "And no surprise - it has most of the components of a functioning perpetual motion device but the most important part - the momentum accelerator - is absent. But you can see exactly where it should go.",
	boxinmachine: "Even now that it contains the {flywheelbox} it's not capable of starting itself.",
	boxfrommachine: "You remove the {flywheelbox} from the {pmm} again.",
	lofttoroof: "[KEEPTRAVEL]Again you drop down onto the {shedroof} and again it holds your weight.",
	flywheelchem: "You don't need to replace the oily liquid in the {flywheelbox} again. The current contents are just fine.",
	crashedpod: "This thing isn't flying any time soon, but you don't need it to. All it had to do was get you here.",
	engineopening: "[STATE:loft=opening]There's an {engineopening} in the side.",
	charging: "Shoved into the middle of the mechanism right next to the cylinder is the {flywheelbox}. Both flywheels are spinning at breakneck speed.",
	diaryinroom: "There's a {diary} on the desk.",
	pmmworking: "The {pmm} is now fully operational and encased in a shimmering bubble of energy which will stop it being reset when the exclusion field dissipates. Beneath it is an open {drawer}.",
	inclusion: "[STATE:final=send]You take a step back, remove a small metal device from your jacket's inside pocket and draw, quite expertly, a shape in the air around the {pmm}. As you complete the shape there is a snap of static electricity and the shape becomes a sparkling, rippling bubble. You've done what you came here to do. You stand for a second in the middle of the {bedroom} and take a breath. Time to go.",
	wayout: "The {lawn} and {flowers} are just as tall as they were before but they're now dwarfed somewhat by a {tear} around 8 metres tall and 3 metres wide which hangs silently above the grass.",
	intotear: "[LOSE:*][STATE:garden=hide][STATE:final=keepgoing]You step forwards and the exclusion field collapses behind you. Your drop-pod vanishes in a puff of logic; the roof and back wall reform; the handle reappears on the bedroom door. Even the clock in the lounge starts ticking forwards. # Everything resets, that is, except for the perpetual motion device. The perspex box is no longer at the bottom of the stairs - it's now upstairs surrounded by whirring cogs and pulleys. # You see none of this, of course; you just know it, because that's the state in which you found it that fateful afternoon, once your parents caught up with you, asked why they'd seen you jump out of your bedroom window and made you turn around and come home. # The {tear} vanishes from the garden.",
	thisway: "<I>&quot;Come on. It's {thisway}.&quot;</I>",
	url_survey: "https://www.surveymonkey.co.uk/r/DWBSMNN"
}
